version: '3.9'

services:
#-------------------frontend-------------------#
  frontend:
    image: dhruvmoradiya69000/mern-frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - mern-network
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:3000
#-------------------backend-------------------#
  backend:
    image: dhruvmoradiya69000/mern-backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_CONNECTION_STRING=mongodb+srv://admin:test%401234@bookingappdb.xwa1ktx.mongodb.net/?retryWrites=true&w=majority&appName=bookingappdb
      - JWT_SECRET_KEY=h0iNngecVP6g7D2eC4xOUoWZLQJ4KoV1
      - CLOUDINARY_CLOUD_NAME=dqgjtaxsf
      - CLOUDINARY_API_KEY=551623449475562
      - CLOUDINARY_API_SECRET=QZU-ZmyjcmSe6XuwivVTNDa3-wc
      - STRIPE_API_KEY=sk_test_51Pt1NbKc0T39VS5S0l4GaLC6qMMyP0jrH5hVmP7I6KvSdErcvdsAxtkeaD8XpklFcl1hvVg9PFczImCCZbFjEQys00nq3b0NCh
    networks:
      - mern-network

#-------------------network-------------------#
networks:
  mern-network:
    driver: bridge

# docker compose up --build -d