apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: mern-app
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dhruvmoradiya69000/mern-backend:latest
          ports:
            - containerPort: 5050
          env:
            - name: MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: all-secrets
                  key: MONGODB_CONNECTION_STRING
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: all-secrets
                  key: JWT_SECRET_KEY
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: all-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: all-secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: all-secrets
                  key: CLOUDINARY_API_SECRET
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: all-secrets
                  key: STRIPE_API_KEY
