apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mern-app-ns
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050