apiVersion: v1
kind: PersistentVolume

metadata:
  name: mern-app-pv
  namespace: mern-app-ns
  labels:
    app: mern-app
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 1Gi
  hostPath:
    path: "/tmp/mern-mongodb"