apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: mern-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb-pod
      namespace: mern-app
      labels: 
        app: mongodb
    spec:
      containers:
      - name: mernapp-mongodb
        image: dhruvmoradiya69000/mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: all-secrets
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: all-secrets
              key: MONGO_INITDB_ROOT_PASSWORD
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongodb-pvc   



