apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mern-app-pvc
  namespace: mern-app-ns
  labels:
    app: mern-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  